# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

#fos_ck_editor:
#    input_sync: true
#    default_config: default
#    configs:
#        default:
#            versionCheck: false
#            toolbar:
#                - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', '-', 'Subscript', 'Superscript', '-', 'RemoveFormat'] }
#                - { name: "paragraph", items: ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote']}
#                - { name: "colors", items: ['TextColor', 'BGColor']}
#                - { name: "links", items: ['Link', 'Unlink']}
#                - { name: "media", items: ['Image', 'Youtube']}
#                - { name: "tools", items: ['Maximize']}
#            extraPlugins: "youtube"
