version: '3.9'

networks:
    default:
        external: true
        name: "${NETWORK}"

services:
  web:
    build: .
    image: "gprodb-v3-${TAG}"
    environment:
      VIRTUAL_HOST: "${TAG}.${DOMAIN}"
      LETSENCRYPT_HOST: "${TAG}.${DOMAIN}"
      APP_VERSION: "${TAG}"
      APP_ENV: "${APP_ENV}"
      JSON_HUB_API_URL: "${JSON_HUB_API_URL}"
      PROJECT_INFO_DEFINITION: "${PROJECT_INFO_DEFINITION}"
      LANDING_PAGE_DEFINITION: "${LANDING_PAGE_DEFINITION}"
      DOMAIN_DEFINITION: "${DOMAIN_DEFINITION}"
      MAILING_PROVIDER_DEFINITION: "${MAILING_PROVIDER_DEFINITION}"
      MAILING_R_CONFIG_DEFINITION: "${MAILING_R_CONFIG_DEFINITION}"
      PROXY_DEFAULT_TARGET_PREFIX: "${PROXY_DEFAULT_TARGET_PREFIX}"
      PAGES_URL_PREFIX: "${PAGES_URL_PREFIX}"
      JSON_HUB_INTERNAL_API_URL: "${JSON_HUB_INTERNAL_API_URL}"
      JSON_HUB_INTERNAL_API_TOKEN: "${JSON_HUB_INTERNAL_API_TOKEN}"
      GPRODB_ENTITY_UUID: "${GPRODB_ENTITY_UUID}"
      AMQP_NEWSLETTER_ROUTING_KEY: "${AMQP_NEWSLETTER_ROUTING_KEY}"
      MESSENGER_TRANSPORT_DSN: "${MESSENGER_TRANSPORT_DSN}"
      MAINTENANCE_MODE: "${MAINTENANCE_MODE}"
