# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $jsonHubUrl: '%env(JSON_HUB_URL)%'
            $jsonHubApiUrl: '%env(JSON_HUB_API_URL)%'
            $projectDefinitionUuid: '%env(PROJECT_INFO_DEFINITION)%'
            $landingPageDefinitionUuid: '%env(LANDING_PAGE_DEFINITION)%'
            $domainDefinitionUuid: '%env(DOMAIN_DEFINITION)%'
            $mailingProviderDefinitionUuid: '%env(MAILING_PROVIDER_DEFINITION)%'
            $mailingRConfigDefinitionUuid: '%env(MAILING_R_CONFIG_DEFINITION)%'
            $pagesUrlPrefix: '%env(PAGES_URL_PREFIX)%'
            $proxyDefaultTargetPrefix: '%env(PROXY_DEFAULT_TARGET_PREFIX)%'
            $internalApiUrl: '%env(JSON_HUB_INTERNAL_API_URL)%'
            $internalApiToken: '%env(JSON_HUB_INTERNAL_API_TOKEN)%'
            $emailSenderAddress: '%env(EMAIL_SENDER_ADDRESS)%'
            $gprodbEntityUuid: '%env(GPRODB_ENTITY_UUID)%'
#            $amqpNewsletterRoutingKey: '%env(AMQP_NEWSLETTER_ROUTING_KEY)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Infrastructure/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Infrastructure\JsonHub\:
        resource: '../src/Infrastructure/JsonHub'

    GProDB\LandingPage\MapperFactory: ~
